# Generated by Django 4.1.7 on 2023-10-11 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route_name', models.CharField(blank=True, default='', max_length=400, null=True)),
                ('lat', models.DecimalField(blank=True, decimal_places=30, max_digits=35, null=True)),
                ('lng', models.DecimalField(blank=True, decimal_places=30, max_digits=35, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('helpers', models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3)], default=1, null=True)),
                ('floors', models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default=0, null=True)),
                ('shuttle', models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Pick up'), (2, 'Drop off'), (3, 'both')], default=0, null=True)),
                ('vehicle_size', models.FloatField(blank=True, choices=[(1.0, '1.0 Ton'), (1.5, '1.5 Ton'), (4.0, '4.0 Ton'), (8.0, '8.0 Ton')], default=1.0, null=True)),
                ('payment_option', models.CharField(blank=True, choices=[('EFT', 'EFT'), ('CASH', 'CASH')], default='CASH', max_length=50, null=True)),
                ('driver_note', models.TextField(blank=True, default='No note left', max_length=1000, null=True)),
                ('hear_about_us', models.CharField(blank=True, choices=[('None', 'None'), ('Facebook', 'Facebook'), ('Gumtree', 'Gumtree'), ('Referral', 'Referral')], default='None', max_length=100, null=True)),
                ('referal_code', models.CharField(blank=True, default='xcrossinglines', max_length=150, null=True)),
                ('referal_discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('base_fee', models.FloatField(blank=True, default=0.0, null=True)),
                ('amount_due', models.FloatField(blank=True, default=0.0, null=True)),
                ('mid_discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('distance', models.FloatField(blank=True, default=0.0, null=True)),
                ('return_customer_discount', models.FloatField(blank=True, default=0.0, null=True)),
                ('job_completed', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('job_canceled', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('job_cancellation_feedback_sent', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('job_invoice_sent', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('feedback_email_sent', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('job_out_sourced', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('give_extra_discount', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('job_date', models.DateField(null=True)),
                ('job_time', models.TimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_identity', to=settings.AUTH_USER_MODEL)),
                ('driver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='driver_identity', to=settings.AUTH_USER_MODEL)),
                ('routes', models.ManyToManyField(blank=True, to='jobs.route')),
            ],
        ),
    ]
