# Generated by Django 4.1.7 on 2023-02-18 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "route_name",
                    models.CharField(blank=True, default="", max_length=400, null=True),
                ),
                (
                    "lat",
                    models.DecimalField(
                        blank=True, decimal_places=30, max_digits=35, null=True
                    ),
                ),
                (
                    "lng",
                    models.DecimalField(
                        blank=True, decimal_places=30, max_digits=35, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("helpers", models.IntegerField(blank=True, default=0, null=True)),
                ("floors", models.IntegerField(blank=True, default=0, null=True)),
                ("vehicle_size", models.FloatField(blank=True, default=1.0, null=True)),
                (
                    "payment_option",
                    models.CharField(
                        blank=True, default="CASH", max_length=50, null=True
                    ),
                ),
                (
                    "driver_note",
                    models.TextField(
                        blank=True, default="No note left", max_length=1000, null=True
                    ),
                ),
                ("service_rating", models.IntegerField(blank=True, default=0)),
                (
                    "referal_code",
                    models.CharField(blank=True, default="", max_length=150, null=True),
                ),
                (
                    "referal_discount",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("quote", models.FloatField(blank=True, default=0.0, null=True)),
                (
                    "middle_month_discount",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                ("distance", models.FloatField(blank=True, default=0.0, null=True)),
                ("job_completed", models.BooleanField(default=False)),
                ("job_canceled", models.BooleanField(default=False)),
                ("job_date", models.DateField(null=True)),
                ("job_time", models.TimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer_identity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "driver",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="driver_identity",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("routes", models.ManyToManyField(blank=True, to="jobs.route")),
            ],
        ),
    ]
