# Generated by Django 4.1.7 on 2023-11-05 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_vehicle_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='extra_discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
