# Generated by Django 4.1.7 on 2023-11-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_job_extra_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='price_adjustment',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='set_price_adjustment',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
    ]
