# Generated by Django 4.1.7 on 2023-11-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_job_price_adjustment_job_set_price_adjustment'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='extra_discount_pecentage',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
