# Generated by Django 4.1.7 on 2023-03-10 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0004_alter_job_vehicle_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="floors",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (0, 0),
                    (1, 1),
                    (2, 2),
                    (3, 3),
                    (4, 4),
                    (5, 5),
                    (6, 6),
                    (7, 7),
                    (8, 8),
                    (9, 9),
                    (10, 10),
                ],
                default=0,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="helpers",
            field=models.IntegerField(
                blank=True, choices=[(1, 1), (2, 2), (3, 3)], default=1, null=True
            ),
        ),
    ]
