# Generated by Django 4.1.7 on 2023-03-20 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0005_alter_job_floors_alter_job_helpers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="job_canceled",
            field=models.BooleanField(
                choices=[(False, "no"), (True, "yes")], default=False
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="job_completed",
            field=models.BooleanField(
                choices=[(False, "no"), (True, "yes")], default=False
            ),
        ),
    ]
