# Generated by Django 4.1.7 on 2023-11-06 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_job_price_adjustment_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='extra_discount',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='job',
            name='extra_discount_pecentage',
            field=models.FloatField(blank=True, default=0.0),
        ),
        migrations.AlterField(
            model_name='job',
            name='price_adjustment',
            field=models.FloatField(blank=True, default=0.0),
        ),
    ]
