# Generated by Django 4.1.7 on 2023-11-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_alter_job_extra_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='extra_discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='extra_discount_pecentage',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='job',
            name='price_adjustment',
            field=models.FloatField(default=0.0),
        ),
    ]
