# Generated by Django 4.1.7 on 2023-05-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_amount_due_alter_job_job_canceled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='shuttling',
            field=models.IntegerField(blank=True, choices=[(0, 0), (1, 1), (2, 2)], default=0, null=True),
        ),
    ]
