# Generated by Django 4.1.7 on 2023-05-08 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_job_shuttling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='shuttling',
            new_name='shuttle',
        ),
    ]
