# Generated by Django 4.1.7 on 2023-11-11 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_route_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='description',
            field=models.IntegerField(blank=True, choices=[(0, 'Pickup'), (1, 'Dropoff'), (2, 'Both')], default=2, null=True),
        ),
    ]
