# Generated by Django 4.1.7 on 2023-05-10 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_rename_shuttling_job_shuttle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='shuttle',
        ),
    ]
