# Generated by Django 4.1.7 on 2023-05-24 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_remove_job_shuttle'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='hear_about_us',
            field=models.TextField(blank=True, default='GUMTREE', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='vehicle_size',
            field=models.FloatField(blank=True, choices=[(1.0, '1.0 Ton'), (1.5, '1.5 Ton'), (4.0, '4.0 Ton'), (8.0, '8.0 Ton')], default=1.0, null=True),
        ),
    ]
