# Generated by Django 4.1.7 on 2026-03-01 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0011_alter_job_vehicle_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="set_price_adjustment",
            field=models.BooleanField(
                choices=[(False, "No"), (True, "Yes")], default=True
            ),
        ),
    ]
