# Generated by Django 4.1.7 on 2023-05-24 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_job_hear_about_us_alter_job_vehicle_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='hear_about_us',
            field=models.CharField(blank=True, default='GUMTREE', max_length=100, null=True),
        ),
    ]
