# Generated by Django 4.1.7 on 2026-03-01 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0012_alter_job_set_price_adjustment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="price_adjustment",
            field=models.FloatField(
                default=0.0,
                help_text="This is the amount that will be added or subtracted from the base fee. Use negative values for discounts and positive values for surcharges.",
            ),
        ),
    ]
