# Generated by Django 4.1.7 on 2026-03-08 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0013_alter_job_price_adjustment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="price_adjustment",
            field=models.TextField(
                default="0.0",
                help_text="This is the amount that will be added or subtracted from the base fee. Use negative values for discounts and positive values for surcharges.",
            ),
        ),
    ]
