# Generated by Django 4.1.7 on 2023-07-01 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0014_alter_job_payment_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='return_customer_discount',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
