# Generated by Django 4.1.7 on 2023-07-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0015_job_return_customer_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_invoice_sent',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
    ]
