# Generated by Django 4.1.7 on 2023-07-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_job_job_out_sourced_alter_job_referal_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='feedback_email_sent',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
    ]
