# Generated by Django 4.1.7 on 2023-07-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_job_feedback_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='service_rating',
        ),
    ]
