# Generated by Django 4.1.7 on 2023-07-10 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_remove_job_service_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='shuttle',
            field=models.IntegerField(blank=True, choices=[(0, 'None'), (1, 'Pick up'), (2, 'Drop off'), (3, 'both')], default=0, null=True),
        ),
    ]
