# Generated by Django 4.1.7 on 2023-07-12 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_job_shuttle'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='give_extra_discount',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
    ]
