# Generated by Django 4.1.7 on 2023-11-11 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotejobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteroutes',
            name='description',
            field=models.IntegerField(blank=True, choices=[(0, 'Pickup'), (1, 'Dropoff'), (2, 'Both')], default=2, null=True),
        ),
    ]
