# Generated by Django 4.1.7 on 2023-10-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_id', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('service_commentry', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('website_commentry', models.CharField(blank=True, default='', max_length=250, null=True)),
                ('service_rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('website_rating', models.FloatField(blank=True, default=0.0, null=True)),
                ('allow_display', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
