# Generated by Django 4.1.7 on 2023-10-11 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('f_name', models.CharField(default='', max_length=150, null=True)),
                ('s_name', models.CharField(default='', max_length=150, null=True)),
                ('m_number', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('register_method', models.IntegerField(blank=True, choices=[(0, 'Email'), (1, 'Google')], default=0, null=True)),
                ('d_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('d_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True)),
                ('verified', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True)),
                ('did_accept_ts_cs', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True)),
                ('is_staff', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('is_corperate', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('customer', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('driver', models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AccountProfile',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('referal_code', models.CharField(max_length=150, unique=True)),
                ('id_number', models.PositiveBigIntegerField(blank=True, null=True)),
                ('use_crossing_lines_for', models.CharField(blank=True, default='private', max_length=150, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
