# Generated by Django 4.1.7 on 2023-03-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="m_number",
            field=models.CharField(blank=True, default="", max_length=50, null=True),
        ),
    ]
