# Generated by Django 4.1.7 on 2023-03-11 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_account_m_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="f_name",
            field=models.CharField(default="", max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="s_name",
            field=models.CharField(default="", max_length=150, null=True),
        ),
    ]
