# Generated by Django 4.1.7 on 2023-07-01 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_f_name_alter_account_s_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_cooperate',
            field=models.BooleanField(default=False),
        ),
    ]
