# Generated by Django 4.1.7 on 2023-07-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_is_cooperate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='customer',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='did_accept_ts_cs',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='driver',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_active',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_cooperate',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='is_staff',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=False),
        ),
        migrations.AlterField(
            model_name='account',
            name='verified',
            field=models.BooleanField(choices=[(False, 'No'), (True, 'Yes')], default=True),
        ),
    ]
