# Generated by Django 4.1.7 on 2023-07-05 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_customer_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='is_cooperate',
            new_name='is_corperate',
        ),
    ]
